// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * Branding is the GetBranding payload. Unset or rejected fields are empty.
 */
export class Branding {
    "title": string;
    "tagline": string;
    "helpUrl": string;
    "helpLabel": string;
    "accent": string;
    "logoMime": string;
    "logoBase64": string;

    /** Creates a new Branding instance. */
    constructor($$source: Partial<Branding> = {}) {
        if (!("title" in $$source)) {
            this["title"] = "";
        }
        if (!("tagline" in $$source)) {
            this["tagline"] = "";
        }
        if (!("helpUrl" in $$source)) {
            this["helpUrl"] = "";
        }
        if (!("helpLabel" in $$source)) {
            this["helpLabel"] = "";
        }
        if (!("accent" in $$source)) {
            this["accent"] = "";
        }
        if (!("logoMime" in $$source)) {
            this["logoMime"] = "";
        }
        if (!("logoBase64" in $$source)) {
            this["logoBase64"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Branding instance from a string or object.
     */
    static createFrom($$source: any = {}): Branding {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Branding($$parsedSource as Partial<Branding>);
    }
}
