// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class AcceptedOperation {
    "operationId"?: string;
    "accepted": boolean;
    "queuedAtUtc": string;

    /**
     * RequestedBy is the user who called, as the service resolved it from the
     * connection: DOMAIN\user on Windows, "" when unresolved.
     */
    "requestedBy": string;

    /** Creates a new AcceptedOperation instance. */
    constructor($$source: Partial<AcceptedOperation> = {}) {
        if (!("accepted" in $$source)) {
            this["accepted"] = false;
        }
        if (!("queuedAtUtc" in $$source)) {
            this["queuedAtUtc"] = "";
        }
        if (!("requestedBy" in $$source)) {
            this["requestedBy"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AcceptedOperation instance from a string or object.
     */
    static createFrom($$source: any = {}): AcceptedOperation {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AcceptedOperation($$parsedSource as Partial<AcceptedOperation>);
    }
}

/**
 * OptionalInstallItem is one offered self-service item. IsRequired is whether
 * an admin manifest also lists it in managed_installs: it is installed for
 * everyone and cannot be removed through self-service.
 */
export class OptionalInstallItem {
    "itemName": string;
    "displayName": string;
    "version": string;
    "catalog": string;
    "description"?: string;
    "category"?: string;
    "developer"?: string;
    "iconName"?: string;
    "restartAction"?: string;
    "isManaged": boolean;
    "isRequired": boolean;
    "isInstalled": boolean;
    "status": string;
    "statusUpdatedAtUtc": string;
    "lastOperationId"?: string;

    /** Creates a new OptionalInstallItem instance. */
    constructor($$source: Partial<OptionalInstallItem> = {}) {
        if (!("itemName" in $$source)) {
            this["itemName"] = "";
        }
        if (!("displayName" in $$source)) {
            this["displayName"] = "";
        }
        if (!("version" in $$source)) {
            this["version"] = "";
        }
        if (!("catalog" in $$source)) {
            this["catalog"] = "";
        }
        if (!("isManaged" in $$source)) {
            this["isManaged"] = false;
        }
        if (!("isRequired" in $$source)) {
            this["isRequired"] = false;
        }
        if (!("isInstalled" in $$source)) {
            this["isInstalled"] = false;
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("statusUpdatedAtUtc" in $$source)) {
            this["statusUpdatedAtUtc"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new OptionalInstallItem instance from a string or object.
     */
    static createFrom($$source: any = {}): OptionalInstallItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new OptionalInstallItem($$parsedSource as Partial<OptionalInstallItem>);
    }
}
